/* flow */

var EDIT_STATES = {
  INITIAL: 0,
  GROUND: 1,
  POINT: 2,
  SEGMENT: 3,
  GROUND_POINT: 4,
  GROUND_GROUND: 5,
  GROUND_TRIANGLE_1: 6,
  GROUND_TRIANGLE_2: 7,
  DYNAMIC_TRIANGLE: 8,
};

var EDIT_INPUT = {
  POINT: 0,
  SEGMENT: 1,
  GROUND: 2
};

var EDIT_STATE_TRANSITIONS = {
  [EDIT_STATES.INITIAL]: {
    [EDIT_INPUT.POINT]: EDIT_STATES.POINT,
    [EDIT_INPUT.SEGMENT]: EDIT_STATES.SEGMENT, 
    [EDIT_INPUT.GROUND]: EDIT_STATES.GROUND,
  },
  [EDIT_STATES.POINT]: {
    [EDIT_INPUT.POINT]: EDIT_STATES.SEGMENT,
    [EDIT_INPUT.SEGMENT]: EDIT_STATES.SEGMENT, 
    [EDIT_INPUT.GROUND]: EDIT_STATES.GROUND_POINT,
  },
  [EDIT_STATES.SEGMENT]: {
    [EDIT_INPUT.POINT]: EDIT_STATES.POINT,
    [EDIT_INPUT.SEGMENT]: EDIT_STATES.SEGMENT, 
    [EDIT_INPUT.GROUND]: EDIT_STATES.DYNAMIC_TRIANGLE,
  },
  [EDIT_STATES.GROUND]: {
    [EDIT_INPUT.POINT]: EDIT_STATES.POINT,
    [EDIT_INPUT.SEGMENT]: EDIT_STATES.SEGMENT,
    [EDIT_INPUT.GROUND]: EDIT_STATES.GROUND_GROUND,
  },
  [EDIT_STATES.GROUND_POINT]: {
    [EDIT_INPUT.POINT]: EDIT_STATES.DYNAMIC_TRIANGLE,
    [EDIT_INPUT.SEGMENT]: EDIT_STATES.SEGMENT, 
    [EDIT_INPUT.GROUND]: EDIT_STATES.GROUND_TRIANGLE_1,
  },
  [EDIT_STATES.GROUND_GROUND]: {
    [EDIT_INPUT.POINT]: EDIT_STATES.GROUND_TRIANGLE_2,
    [EDIT_INPUT.SEGMENT]: EDIT_STATES.SEGMENT, 
    [EDIT_INPUT.GROUND]: EDIT_STATES.GROUND,
  },
};

module.exports = {
  EDIT_STATES,
  EDIT_INPUT,
  EDIT_STATE_TRANSITIONS,
};
